# Generated by Django 4.1.2 on 2022-10-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_question_response_alter_category_image_delete_faq_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='response',
            field=models.ManyToManyField(blank=True, related_name='response_of_question', to='faq.response'),
        ),
    ]
